### ISSUE TITLE
[Feature request]: Add the ability to execute a command or open the overview by clicking on the spacer

### ISSUE THREAD

**Issue by darhma** [eatsu/plasmoid-spacer-as-pager#1]
Just these days I was looking for an applet similar to this, thanks. For me it would be perfect if in addition to using the mouse wheel you could set a customizable command to execute if the spacer is left clicked, or at least have the possibility to open the overview by left clicking on the spacer

**Comment by eatsu** [comment]
Sounds interesting, thanks for the suggestion. I'll look into it.

**Comment by eatsu** [comment]
Implemented :tada:
